---
name: "Pull Requests"
"on":
  pull_request:
    branches:
    - "main"
jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      checks: "write"
      pull-requests: "write"
    steps:
    - uses: "actions/checkout@v4"
    - name: "Set up JDK"
      uses: "actions/setup-java@v4"
      with:
        java-version: "21"
        distribution: "temurin"
    - name: "Setup Gradle"
      uses: "gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582"
    - name: "Test"
      run: "./gradlew check"
    - name: "Publish Test Results"
      uses: "EnricoMi/publish-unit-test-result-action@v2"
      if: "always()"
      with:
        files: "**/test-results/**/*.xml"
  dependency-submission:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
    - uses: "actions/checkout@v4"
    - name: "Set up JDK 21"
      uses: "actions/setup-java@v4"
      with:
        java-version: "21"
        distribution: "temurin"
    - name: "Generate and submit dependency graph"
      uses: "gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582"
